version: '3.8'

services:
  web:
    build: .
    container_name: my_django_app
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/feeda
    ports:
      - '8000:8000'

volumes:
  db_data:
